version: '3.1'

services:

  db:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - lambda-server-network
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_USER=admin
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - '5050:80'
      depends_on:
        - db
      volumes:
        - ./pgadmin4/servers.json:/pgadmin4/servers.json
      networks:
        - lambda-server-network
networks:
  lambda-server-network:
volumes:
  pg_data: