ALTER TABLE course_registers
    DROP CONSTRAINT fk_course_registers_on_course_class;

ALTER TABLE timing_registers
    DROP CONSTRAINT fk_timing_registers_on_course_class_course_class;

ALTER TABLE course_classes
    DROP COLUMN capacity_so_far;

ALTER TABLE course_classes
    DROP COLUMN course_semester;

ALTER TABLE course_classes
    DROP COLUMN course_state;

ALTER TABLE course_classes
    DROP COLUMN publish_date;

ALTER TABLE course_classes
    DROP COLUMN year;

ALTER TABLE timing_registers
    DROP COLUMN course_class_course_class_id;



ALTER TABLE course_classes
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE course_classes
    DROP COLUMN course_class_id;
ALTER TABLE course_classes
    ADD CONSTRAINT pk_course_classes PRIMARY KEY (id);

ALTER TABLE course_classes
    ADD semester VARCHAR(255);
ALTER TABLE course_classes
    ALTER COLUMN semester SET NOT NULL;

ALTER TABLE course_classes
    ADD state VARCHAR(255);

ALTER TABLE course_classes
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE course_classes
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE course_classes
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE course_classes
    ADD admin_professor_id BIGINT;
ALTER TABLE course_classes
    ALTER COLUMN admin_professor_id SET NOT NULL;

ALTER TABLE course_classes
    ADD year INTEGER NOT NULL DEFAULT 0;
ALTER TABLE course_classes
    ALTER COLUMN year SET NOT NULL;

ALTER TABLE course_classes
    ALTER COLUMN course_id SET NOT NULL;

ALTER TABLE course_classes
    ALTER COLUMN group_number_seq SET NOT NULL;

ALTER TABLE course_classes
    ALTER COLUMN max_capacity SET NOT NULL;
ALTER TABLE course_classes
    ALTER COLUMN max_capacity SET DEFAULT 0;

ALTER TABLE course_classes
    ALTER COLUMN number_of_students_registered SET NOT NULL;
ALTER TABLE course_classes
    ALTER COLUMN number_of_students_registered SET DEFAULT 0;


ALTER TABLE timing_registers
    ADD course_class_id BIGINT;


ALTER TABLE course_classes
    ADD CONSTRAINT FK_COURSE_CLASSES_ON_ADMIN_PROFESSOR FOREIGN KEY (admin_professor_id) REFERENCES professors (id);

ALTER TABLE course_registers
    ADD CONSTRAINT FK_COURSE_REGISTERS_ON_COURSE_CLASS FOREIGN KEY (course_class_id) REFERENCES course_classes (id);

ALTER TABLE timing_registers
    ADD CONSTRAINT FK_TIMING_REGISTERS_ON_COURSE_CLASS FOREIGN KEY (course_class_id) REFERENCES course_classes (id);

ALTER TABLE course_classes_professors
    ADD CONSTRAINT fk_couclapro_on_course_class FOREIGN KEY (course_class_id) REFERENCES course_classes (id);

ALTER TABLE course_classes_professors
    ADD CONSTRAINT fk_couclapro_on_professor FOREIGN KEY (professor_id) REFERENCES professors (id);
