CREATE TABLE settings
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key   VARCHAR(255)                            NOT NULL,
    value VARCHAR,
    CONSTRAINT pk_settings PRIMARY KEY (id)
);

ALTER TABLE settings
    ADD CONSTRAINT uc_settings_key UNIQUE (key);