CREATE TABLE course_class_groups
(
    class_group_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_class_id               BIGINT,
    max_capacity                  INTEGER,
    number_of_students_registered INTEGER,
    group_number                  INTEGER,
    CONSTRAINT pk_course_class_groups PRIMARY KEY (class_group_id)
);

CREATE TABLE course_classes
(
    course_class_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id                            BIGINT,
    publish_date                  date,
    course_semester               VARCHAR(255),
    course_state                  VARCHAR(255),
    max_capacity                  INTEGER,
    number_of_students_registered INTEGER,
    capacity_so_far               INTEGER,
    group_number_seq              INTEGER,
    CONSTRAINT pk_course_classes PRIMARY KEY (course_class_id)
);

ALTER TABLE course_classes
    ADD CONSTRAINT FK_COURSE_CLASSES_ON_ID FOREIGN KEY (id) REFERENCES courses (id);

ALTER TABLE course_class_groups
    ADD CONSTRAINT FK_COURSE_CLASS_GROUPS_ON_COURSE_CLASS FOREIGN KEY (course_class_id) REFERENCES course_classes (course_class_id);